# -*- coding: utf-8 -*-
"""Validador Automático de Notas Fiscais (CSV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15-FouxC2HEyDXt2KRNtHPXpNAJWn9SvT

Importação das Bibliotecas
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from openpyxl import Workbook
from openpyxl.styles import PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows
import xml.etree.ElementTree as ET
import pandas as pd
import re

from google.colab import files
uploaded = files.upload()

xml_files = [name for name in uploaded.keys()]
xml_files

def parse_nfe_xml(file):
    tree = ET.parse(file)
    root = tree.getroot()

    # Namespace padrão da NF-e
    ns = {"ns": "http://www.portalfiscal.inf.br/nfe"}

    # Identificação da NFe
    ide = root.find(".//ns:ide", ns)
    emit = root.find(".//ns:emit", ns)
    dest = root.find(".//ns:dest", ns)
    total = root.find(".//ns:ICMSTot", ns)
    prod = root.find(".//ns:det/ns:prod", ns)

    # Dados principais
    numero = ide.find("ns:nNF", ns).text if ide is not None else None
    serie = ide.find("ns:serie", ns).text if ide is not None else None
    data = ide.find("ns:dhEmi", ns).text if ide is not None else None

    # CNPJ
    cnpj_emit = emit.find("ns:CNPJ", ns).text if emit is not None else None
    cnpj_dest = dest.find("ns:CNPJ", ns).text if dest is not None else None

    # Valores
    vNF = total.find("ns:vNF", ns).text if total is not None else None
    vProd = total.find("ns:vProd", ns).text if total is not None else None

    # CFOP do 1º item
    cfop = prod.find("ns:CFOP", ns).text if prod is not None else None

    # Chave de acesso
    chave_tag = root.find(".//ns:infNFe", ns)
    chave = chave_tag.attrib.get("Id", "").replace("NFe", "") if chave_tag is not None else None

    return {
        "numero_nf": numero,
        "serie": serie,
        "data_emissao": data,
        "cnpj_emitente": cnpj_emit,
        "cnpj_destinatario": cnpj_dest,
        "valor_nf": vNF,
        "valor_produtos": vProd,
        "cfop": cfop,
        "chave_acesso": chave
    }

notas = []

for f in xml_files:
    try:
        dados = parse_nfe_xml(f)
        notas.append(dados)
    except Exception as e:
        print(f"Erro ao processar {f}: {e}")

df_xml = pd.DataFrame(notas)
df_xml

"""Validação de CNPJ"""

def validar_cnpj(cnpj):
    cnpj = ''.join(filter(str.isdigit, str(cnpj)))
    if len(cnpj) != 14:
        return False

    def calcular_dv(cnpj, peso):
        soma = sum(int(cnpj[i]) * peso[i] for i in range(len(peso)))
        resto = soma % 11
        return '0' if resto < 2 else str(11 - resto)

    peso1 = [5,4,3,2,9,8,7,6,5,4,3,2]
    dv1 = calcular_dv(cnpj, peso1)

    peso2 = [6] + peso1
    dv2 = calcular_dv(cnpj, peso2)

    return cnpj[-2:] == dv1 + dv2

"""Carregar CSV e Normalizar Dados"""

df = df_xml.copy()

df["data_emissao"] = pd.to_datetime(df["data_emissao"], errors="coerce").dt.tz_localize(None) # Remove timezone information
df["valor_nf"] = df["valor_nf"].astype(float)
# O valor_pedido não existe em df_xml, preciso criá-lo ou remover a linha
# Por simplicidade, vou assumir que o valor do produto é o valor do pedido para este exemplo.
df["valor_pedido"] = df["valor_produtos"].astype(float)

df["cnpj_emitente_valido"] = df["cnpj_emitente"].apply(validar_cnpj)
df["cnpj_destinatario_valido"] = df["cnpj_destinatario"].apply(validar_cnpj)

csv_filename = "notas_fiscais_processadas.csv"
df_xml.to_csv(csv_filename, index=False)

print(f"Arquivo '{csv_filename}' gerado com sucesso!")

from google.colab import files
files.download(csv_filename)

"""Regras de validação"""

# === 3. Criar colunas de validação ===
df["validacao_cnpj_emitente"] = df["cnpj_emitente"].apply(validar_cnpj)
df["validacao_cnpj_destinatario"] = df["cnpj_destinatario"].apply(validar_cnpj)

# === 4. Detectar duplicidade de NF ===
df["duplicidade"] = df.duplicated(subset=["numero_nf"], keep=False)

# === 5. Divergência entre valor NF e valor do pedido ===
df["divergencia_valor"] = df["valor_nf"] != df["valor_pedido"]

# === 6. Lista de CFOP válidos (exemplo) ===
cfop_validos = ["5101", "5102", "6101", "6102"]

df["cfop_valido"] = df["cfop"].astype(str).isin(cfop_validos)

# === 7. Criar coluna final de status ===
def status_linha(linha):
    erros = []
    if not linha["validacao_cnpj_emitente"]:
        erros.append("CNPJ Emitente Inválido")
    if not linha["validacao_cnpj_destinatario"]:
        erros.append("CNPJ Destinatário Inválido")
    if linha["duplicidade"]:
        erros.append("Nota Fiscal Duplicada")
    if linha["divergencia_valor"]:
        erros.append("Valor Divergente")
    if not linha["cfop_valido"]:
        erros.append("CFOP Inválido")
    return "; ".join(erros) if erros else "OK"

df["status_validacao"] = df.apply(status_linha, axis=1)

df["duplicada"] = df.duplicated(subset=["numero_nf"], keep=False)
df["valor_divergente"] = df["valor_nf"] != df["valor_pedido"]

cfops_validos = ["5101","5102","6101","6102","5405","6406"]
df["cfop_valido"] = df["cfop"].astype(str).isin(cfops_validos)

"""Coluna consolidada de status"""

def consolidar_status(linha):
    erros = []
    if not linha["cnpj_emitente_valido"]:
        erros.append("CNPJ Emitente Inválido")
    if not linha["cnpj_destinatario_valido"]:
        erros.append("CNPJ Destinatário Inválido")
    if linha["duplicada"]:
        erros.append("NF Duplicada")
    if linha["valor_divergente"]:
        erros.append("Valor Divergente")
    if not linha["cfop_valido"]:
        erros.append("CFOP Inválido")

    return "; ".join(erros) if erros else "OK"

df["status"] = df.apply(consolidar_status, axis=1)

"""Gerar Excel Final com Cores (OpenPyXL) | 🟥 Vermelho → Erro grave
🟧 Amarelo → Aviso (divergência leve)
🟩 Verde → OK
"""

wb = Workbook()
ws = wb.active
ws.title = "Validacao NF"

for r in dataframe_to_rows(df, index=False, header=True):
    ws.append(r)

red = PatternFill(start_color='FFC7CE', end_color='FFC7CE', fill_type='solid')
yellow = PatternFill(start_color='FFEB9C', end_color='FFEB9C', fill_type='solid')
green = PatternFill(start_color='C6EFCE', end_color='C6EFCE', fill_type='solid')

for row in ws.iter_rows(min_row=2):
    status = row[df.columns.get_loc("status")].value

    if status == "OK":
        for cell in row:
            cell.fill = green

    elif "Valor Divergente" in status:
        for cell in row:
            cell.fill = yellow

    else:
        for cell in row:
            cell.fill = red

wb.save("relatorio_validacao_nf.xlsx")

"""Dashboard simples (Matplotlib)"""

# NF por dia
df.groupby(df["data_emissao"].dt.date)["numero_nf"].count().plot(kind="bar")
plt.title("Notas Emitidas por Dia")
plt.xlabel("Data")
plt.ylabel("Quantidade")
plt.show()

# Divergências detectadas
df["status"].value_counts().plot(kind="bar")
plt.title("Distribuição dos Status de Validação")
plt.xlabel("Status")
plt.ylabel("Quantidade")
plt.show()

"""Resumo Final"""

resumo = {
    "Total NFs": len(df),
    "CNPJ Inválido": (~df["cnpj_emitente_valido"] | ~df["cnpj_destinatario_valido"]).sum(),
    "Duplicadas": df["duplicada"].sum(),
    "Divergência de Valor": df["valor_divergente"].sum(),
    "CFOP Inválido": (~df["cfop_valido"]).sum(),
    "OK": (df["status"] == "OK").sum()
}

pd.DataFrame(resumo, index=[0])

import matplotlib.pyplot as plt

# Gráfico 1 - Notas por dia
plt.figure(figsize=(10,5))
df.groupby(df["data_emissao"].dt.date)["numero_nf"].count().plot(kind="bar")
plt.title("Notas Emitidas por Dia")
plt.xlabel("Data")
plt.ylabel("Quantidade")
plt.tight_layout()
plt.savefig("grafico_notas_por_dia.png", dpi=300)
plt.close()

# Gráfico 2 - Distribuição dos Status
plt.figure(figsize=(10,5))
df["status"].value_counts().plot(kind="bar")
plt.title("Distribuição dos Status de Validação")
plt.xlabel("Status")
plt.ylabel("Quantidade")
plt.tight_layout()
plt.savefig("grafico_status_validacao.png", dpi=300)
plt.close()

resumo = {
    "Total NFs": len(df),
    "CNPJ Inválido": (~df["cnpj_emitente_valido"] | ~df["cnpj_destinatario_valido"]).sum(),
    "Duplicadas": df["duplicada"].sum(),
    "Divergência de Valor": df["valor_divergente"].sum(),
    "CFOP Inválido": (~df["cfop_valido"]).sum(),
    "OK": (df["status"] == "OK").sum()
}

resumo_df = pd.DataFrame(resumo, index=[0])
resumo_df

import matplotlib.pyplot as plt

# Create a figure and a set of subplots
fig, ax = plt.subplots(figsize=(10, 2))
ax.axis('off') # Hide axes

# Create the table
table = ax.table(cellText=resumo_df.values,
                     colLabels=resumo_df.columns,
                     loc='center')

# Adjust layout and save the figure
table.auto_set_font_size(False)
table.set_fontsize(12)
table.scale(1.2, 1.2)
fig.tight_layout()
plt.savefig("tabela_resumo.png", dpi=300)
plt.close()

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(12, 6))
ax.axis('off')

table = ax.table(cellText=df.head(20).values,
                     colLabels=df.head(20).columns,
                     loc='center')

table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.2)
fig.tight_layout()
plt.savefig("df_validado_preview.png", dpi=300)
plt.close()